#!/bin/bash -e

# Host->BT
#gpioset -c gpiochip8 4=1 &
# BT->Host
#gpioset -c gpiochip8 3=1 &
# WL->Host
#gpioset -c gpiochip8 6=1 &

btwake
btreset
# Bluetooth
modprobe hci_uart
rtk_hciattach -n -s 115200 ttySTM6 rtk_h5 &

# Close WiFi log
echo 0 > /proc/net/rtl8821cs/log_level
